before_script:
  - gem install rdoc
  - gem install hoe
  - gem install rake-compiler
  - gem install mini_portile
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
env:
  - USE_MINI_PORTILE=true
  - USE_MINI_PORTILE=false
notifications:
  email:
    - aaron@tenderlovemaking.com
    - luislavena@gmail.com
