language: ruby
cache: bundler
before_install:
  - |
      rv="$(ruby -e 'STDOUT.write RUBY_VERSION')";
      if   [ "$rv" \< "2.3" ]; then gem update --system 2.7.9 --no-document
      elif [ "$rv" \< "2.6" ]; then gem update --system --no-document --conservative
      fi
  - |
    rv="$(ruby -e 'STDOUT.write RUBY_VERSION')";
    if   [ "$rv" \< "2.3" ]; then gem install bundler -v 1.17.3
    elif [ "$rv" \< "2.6" ]; then gem install bundler
    fi
addons:
  apt:
    packages:
      - libgmp-dev

after_failure:
  - "find . -name mkmf.log -exec cat {} \\;"

after_success:
  - "find . -name mkmf.log -exec cat {} \\;"

env:
  - USE_MINI_PORTILE=true
  - USE_MINI_PORTILE=false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
matrix:
  allow_failures:
    - env: USE_MINI_PORTILE=false
